os_unfair_lock
kean/FutureX pull request #7
Opened 2019-11-14 21:09 UTC by moto0000

Few days ago I found a very interesting way to make locekd value:
https://github.com/SvenTiigi/CodableStoreKit/blob/master/Sources/Extensions/Locked.swift

Benchmark:
https://gist.github.com/steipete/36350a8a60693d440954b95ea6cbbafc

Article:
https://www.mikeash.com/pyblog/friday-qa-2017-10-27-locks-thread-safety-and-swift-2017-edition.html

2019-11-17 01:16 UTC, kean commented
Thanks, @moto0000. I'm considering using spin locks. I think it can be a major win in this case.

2019-11-17 18:15 UTC, kean requested changes
I'm in favor of merging this. This was the last thing that I wanted to optimize for a while. I think after this change, FutureX might be *the fastest* future implementation out there. Thanks again, @moto0000, for putting this together.

2019-11-17 18:15 UTC, kean commented on Sources/Future.swift
> +            guard let result = self.memoizedResult.value else {
AFAIR this lock is used not only to synchronize access to `memoizedResult`, but also to `handlers` and `inlineHandler`.

2019-11-17 18:15 UTC, kean commented on Sources/Future.swift
>          private let lock = NSLock()
This lock should also be removed in favor of spin lock. This is going to be major win! Instantiating `NSLock` is relatively expensive.

2019-11-17 20:39 UTC, moto0000 commented
@kean I make few changes

2019-11-19 00:58 UTC, kean approved these changes

2019-11-19 03:03 UTC, merged

2019-11-20 02:09 UTC, kean commented
Hey, @moto0000, I ran the performance tests included in the repo and I haven't noticed any performance improvements. I tried using Nuke repo, I also didn't see any performance improvements. These results in [RxSwift](https://github.com/ReactiveX/RxSwift/pull/2042) repo also suggest that there are no noticeable performance improvements.

I think Steinberger's results are no longer relevant. I know for a fact that `NSLock` used to be slow but somewhere in 2016 Apple rewrote it and it now has performance comparable to spin locks in many cases.

I think I will revert these changes and stick with `NSLock` since it's a higher level primitive. There are less chances to run into issue with `NSLock` than with `os_unfair_lock_s`.